# Generated by Django 2.2.7 on 2019-11-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191115_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publicado',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
